# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_version = "20241002.0.0"

  config.vm.hostname = "ubuntu-aria"
  config.vm.network "public_network"

  # config.vm.synced_folder "../data", "/home/vagrant/data", owner: "vagrant", group: "vagrant"
  config.vm.synced_folder "E:/4_bootcamp/idn_bootcamp/final_task/tema7", "/home/vagrant/data", owner: "vagrant", group: "vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true  
    vb.memory = "3039"
    vb.cpus = 3
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
  SHELL
end