# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_version = "20241002.0.0"

  config.vm.hostname = "ubuntu-aria"
  config.vm.network "public_network"

  # config.vm.synced_folder "../data", "/home/vagrant/data", owner: "vagrant", group: "vagrant"
  # config.vm.synced_folder "E:/4_bootcamp/idn_bootcamp/final_task", "/home/vagrant/data", owner: "vagrant", group: "vagrant"
  # config.vm.synced_folder "E:/_test/", "/home/vagrant/_test", owner: "vagrant", group: "vagrant"
  config.vm.synced_folder "E:/7_app/HPone/", "/home/vagrant/data", owner: "vagrant", group: "vagrant"
  config.vm.synced_folder "E:/5_web", "/home/vagrant/web", owner: "vagrant", group: "vagrant"
  config.vm.synced_folder "../scripts/", "/home/vagrant/scripts", owner: "vagrant", group: "vagrant"
  config.vm.synced_folder "../data", "/home/vagrant/linux", owner: "vagrant", group: "vagrant"
  config.vm.synced_folder "E:/8_security/FGTE/", "/home/vagrant/fgte", owner: "vagrant", group: "vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ubuntu"
    vb.gui = false
    vb.memory = "3100"
    vb.cpus = 3
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt install -y curl
    curl -s https://raw.githubusercontent.com/ariafatah0711/vm/refs/heads/main/scripts/setup.sh | bash -s install
    sudo -u vagrant bash -c "curl -s https://raw.githubusercontent.com/ariafatah0711/vm/refs/heads/main/scripts/setup.sh | bash -s install"
  SHELL
end
