# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "kalilinux/rolling"

  # Gunakan bridged network (akan minta pilih adapter fisik saat vagrant up)
  config.vm.network "public_network"
  # config.vm.synced_folder "./data", "/home/vagrant/linux", owner: "vagrant", group: "vagrant"
  config.vm.synced_folder "E:/8_security/ctf_aria", "/home/vagrant/ctf_aria", owner: "vagrant", group: "vagrant"
  config.vm.synced_folder "E:/8_security/btr", "/home/vagrant/data", owner: "vagrant", group: "vagrant"
  # config.vm.synced_folder "E:/8_security/htr_aria", "/home/vagrant/htr_aria", owner: "vagrant", group: "vagrant"

  config.vm.synced_folder "E:/5_web", "/home/vagrant/web", owner: "vagrant", group: "vagrant"

  # VirtualBox specific settings
  config.vm.provider "virtualbox" do |vb|
    vb.name = "kali_linux"

    # Tampilkan GUI saat boot
    vb.gui = true

    # RAM VM
    vb.memory = "5050"
    vb.cpus = 6

     vb.customize ["modifyvm", :id, "--draganddrop", "disabled"]

    # 🔴 Disable NAT adapter bawaan (nic1)
    # vb.customize ["modifyvm", :id, "--nic1", "none"]
  end

  # Provision dengan shell script
  config.vm.provision "shell", inline: <<-EOF
    sudo apt update
    sudo apt install -y crowbar curl
    # curl -s https://raw.githubusercontent.com/ariafatah0711/vm/refs/heads/main/scripts/setup.sh | bash -s install
    # sudo -u vagrant bash -c "curl -s https://raw.githubusercontent.com/ariafatah0711/vm/refs/heads/main/scripts/setup.sh | bash -s install"
  EOF
end
